### ISSUE TITLE
Add AWS Signature support in opensearch-benchmark client

### ISSUE THREAD

**Issue by edzmh96** [opensearch-project/opensearch-benchmark#189] opened 2022-04-28 19:46 UTC
**Is your feature request related to a problem? Please describe.**
Add AWS Signature support in opensearch-benchmark
**Describe the solution you'd like**
I'd like support for AWS Signature by default in opensearch-benchmark, instead of having to pipe requests through a reverse proxy like https://github.com/abutaha/aws-es-proxy

**Describe alternatives you've considered**
Running requests through a local proxy that signs the ES requests

**Additional context**

**Comment by IanHoang** [comment] 2023-03-30 15:07
Duplicate of #158

**Closed by IanHoang** 2023-03-30 15:07 UTC
Labels: enhancement
