### ISSUE TITLE
[BUG] benchmark test_execution fatal crash

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/opensearch-benchmark#203] opened 2022-06-24 21:27 UTC
**Describe the bug**
benchmark test_execution fatal crash

Command used
```
opensearch-benchmark execute_test --pipeline benchmark-only --target-hosts 127.0.0.1:9200,127.0.0.1:9201,127.0.0.1:9202,127.0.0.1:9203,127.0.0.1:9204 --workload percolator --kill-running-processes
```

Output
```
INFO:osbenchmark.actor:Checking capabilities [{'Thespian ActorSystem Name': 'multiprocQueueBase', 'Thespian ActorSystem Version': 1, 'Python Version': (3, 8, 10, 'final', 0), 'Thespian Generation': (3, 10), 'Thespian Version': '1656105733529'}] against requirements [{'coordinator': True}] failed.
[WARNING] Could not terminate all internal processes within timeout. Please check and force-terminate all Benchmark processes.
[ERROR] Cannot execute_test. This test_execution ended with a fatal crash.
```
[benchmark.log](https://github.com/opensearch-project/opensearch-benchmark/files/8981108/benchmark.log)

**Logs**
Attached

**Comment by dreamer-89** [comment] 2022-06-24 22:00
From log file

```
2022-06-24 21:21:19,28 -not-actor-/PID:53376 osbenchmark.actor ERROR Could not initialize internal actor system.
Traceback (most recent call last):
  File "/Users/singhnjb/.pyenv/versions/3.8.10/lib/python3.8/site-packages/osbenchmark/actor.py", line 254, in bootstrap_actor_system
    return thespian.actors.ActorSystem(system_base,
  File "/Users/singhnjb/.pyenv/versions/3.8.10/lib/python3.8/site-packages/thespian/actors.py", line 635, in __init__
    systemBase = self._startupActorSys(
  File "/Users/singhnjb/.pyenv/versions/3.8.10/lib/python3.8/site-packages/thespian/actors.py", line 676, in _startupActorSys
    systemBase = sbc(self, logDefs=logDefs)
```

**Comment by IanHoang** [comment] 2022-08-05 22:46
Hi @dreamer-89,

Thanks for sharing this! Do you mind providing more context on your setup and steps to reproduce the issue?

**Comment by navneet1v** [comment] 2022-10-31 00:42
I recently faced this issue, and it was because I was running the benchmark when my VPN was enabled. As per my understanding benchmark used Rally software internally which is not VPN friendly. I didn't go deep to fix the VPN issue, but the way it worked for me was I stopped my VPN and it worked for me.

Operating System: macOS
URL and Port I was using: localhost:9200

@dreamer-89 please try running the benchmarks in a non VPN environment. There are configs that I see in some rally documentation how to go around it but haven't tried it as of now.

Some reference: https://github.com/RallyTools/RallyRestToolkitForPython/issues/174

**Comment by IanHoang** [comment] 2023-05-16 17:41
@dreamer-89 Are you still experiencing this issue? If so, have you tried @navneet1v's solution? Although this sounds more like a VPN issue, it's also worth mentioning that we have made several fixes since March 2023. I recommend retrying this with the latest OSB version 0.4.1. 

Closing this issue since there hasn't been activity since October 2022. Please feel free to reopen the issue if the problem still exists and you have tried all solutions suggested.

**Closed by IanHoang** 2023-05-16 17:41 UTC
Labels: bug, High Priority
